import type { SurveyQuestion } from './types'

export const SURVEY_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'morning_person',
    type: 'yn',
    text: '평소 일찍 일어나는 편인가요?',
    subText: '알람 없이도 아침에 눈이 떠지는 타입인지 알려주세요',
    category: 'lifestyle',
    weights: {
      yes: { '寅': 3, '卯': 3, '辰': 2, '子': 1 },
      no: { '酉': 2, '戌': 3, '亥': 3, '子': 2 },
    },
  },
  {
    id: 'focus_time',
    type: 'choice',
    text: '가장 집중이 잘 되는\n시간대는 언제인가요?',
    category: 'lifestyle',
    options: [
      { label: '새벽~아침 (5~9시)', value: 'dawn', weights: { '寅': 3, '卯': 3, '辰': 2 } },
      { label: '오전 (9~12시)', value: 'morning', weights: { '辰': 3, '巳': 3 } },
      { label: '오후 (12~18시)', value: 'afternoon', weights: { '午': 3, '未': 3, '申': 2 } },
      { label: '저녁~밤 (18~24시)', value: 'evening', weights: { '酉': 3, '戌': 3, '亥': 2 } },
      { label: '심야 (0~5시)', value: 'latenight', weights: { '子': 3, '丑': 3 } },
    ],
  },
  {
    id: 'extroversion',
    type: 'scale',
    text: '외향적이라는 말을\n자주 듣나요?',
    subText: '1은 매우 내향적, 5는 매우 외향적',
    category: 'personality',
    scaleLabels: { low: '내향적', high: '외향적' },
    scaleWeights: {
      low: { '亥': 2, '子': 3, '丑': 2, '卯': 1 },
      mid: { '辰': 2, '未': 2, '申': 2 },
      high: { '寅': 3, '午': 3, '巳': 2, '戌': 1 },
    },
  },
  {
    id: 'decision_style',
    type: 'choice',
    text: '중요한 결정을 내릴 때\n어떤 스타일인가요?',
    category: 'personality',
    options: [
      { label: '직감과 느낌을 따른다', value: 'intuition', weights: { '巳': 3, '午': 3, '未': 1 } },
      { label: '논리적으로 분석한다', value: 'analysis', weights: { '亥': 3, '子': 2, '申': 2 } },
      { label: '주변 사람들의 의견을 듣는다', value: 'social', weights: { '卯': 2, '辰': 2, '酉': 2 } },
      { label: '시간을 두고 천천히 결정한다', value: 'slow', weights: { '丑': 3, '未': 2, '戌': 2 } },
    ],
  },
  {
    id: 'leadership',
    type: 'yn',
    text: '모임에서 리더 역할을\n자주 맡는 편인가요?',
    category: 'social',
    weights: {
      yes: { '寅': 3, '午': 2, '辰': 2, '巳': 1 },
      no: { '未': 2, '亥': 2, '卯': 2, '丑': 1 },
    },
  },
  {
    id: 'stress_relief',
    type: 'choice',
    text: '스트레스를 받으면\n주로 어떻게 풀어요?',
    category: 'lifestyle',
    options: [
      { label: '운동이나 야외 활동', value: 'exercise', weights: { '寅': 3, '卯': 2, '午': 2 } },
      { label: '혼자만의 시간 (독서, 명상 등)', value: 'alone', weights: { '子': 3, '丑': 2, '亥': 2 } },
      { label: '사람들과 대화하며 해소', value: 'social', weights: { '巳': 2, '午': 3, '酉': 1 } },
      { label: '맛있는 음식이나 쇼핑', value: 'consume', weights: { '未': 3, '辰': 2, '申': 2 } },
    ],
  },
  {
    id: 'change_seeking',
    type: 'scale',
    text: '새로운 변화를\n추구하는 편인가요?',
    subText: '1은 안정 추구, 5는 변화 선호',
    category: 'personality',
    scaleLabels: { low: '안정 추구', high: '변화 선호' },
    scaleWeights: {
      low: { '丑': 3, '未': 2, '戌': 2, '辰': 1 },
      mid: { '酉': 2, '卯': 2, '申': 2 },
      high: { '寅': 3, '巳': 3, '亥': 2, '子': 1 },
    },
  },
  {
    id: 'relationship_value',
    type: 'choice',
    text: '인간관계에서 가장\n중요하게 여기는 것은?',
    category: 'social',
    options: [
      { label: '신뢰와 의리', value: 'trust', weights: { '丑': 3, '戌': 3, '未': 1 } },
      { label: '재미와 자극', value: 'fun', weights: { '午': 3, '巳': 2, '寅': 2 } },
      { label: '배움과 성장', value: 'growth', weights: { '辰': 2, '申': 3, '子': 2 } },
      { label: '편안함과 안정', value: 'comfort', weights: { '亥': 3, '卯': 2, '酉': 2 } },
    ],
  },
  {
    id: 'childhood',
    type: 'yn',
    text: '어릴 때 활발하고\n에너지가 넘치는 편이었나요?',
    category: 'history',
    weights: {
      yes: { '寅': 3, '卯': 2, '午': 2, '巳': 2 },
      no: { '酉': 2, '亥': 2, '子': 2, '丑': 2 },
    },
  },
  {
    id: 'sleep_pattern',
    type: 'choice',
    text: '주로 몇 시쯤\n잠자리에 드나요?',
    category: 'lifestyle',
    options: [
      { label: '10시 이전', value: 'early', weights: { '寅': 2, '卯': 3, '辰': 1 } },
      { label: '10시~12시', value: 'normal', weights: { '午': 2, '未': 2, '申': 2 } },
      { label: '12시~2시', value: 'late', weights: { '酉': 2, '戌': 3, '亥': 2 } },
      { label: '2시 이후', value: 'very_late', weights: { '子': 3, '丑': 3, '亥': 1 } },
    ],
  },
  {
    id: 'life_change',
    type: 'choice',
    text: '인생에서 가장 큰 변화가\n있었던 시기는 언제인가요?',
    subText: '대략적인 나이대를 선택해주세요',
    category: 'history',
    options: [
      { label: '10대 이전', value: 'childhood', weights: { '子': 2, '丑': 2, '寅': 3 } },
      { label: '10~20대', value: 'youth', weights: { '卯': 3, '辰': 2, '巳': 2 } },
      { label: '20~30대', value: 'adult', weights: { '午': 3, '未': 2, '申': 2 } },
      { label: '30대 이후', value: 'mature', weights: { '酉': 2, '戌': 3, '亥': 2 } },
      { label: '아직 모르겠다', value: 'unknown', weights: { '辰': 1, '未': 1, '戌': 1, '丑': 1 } },
    ],
  },
  {
    id: 'intuition',
    type: 'scale',
    text: '직감이 잘 맞는\n편인가요?',
    subText: '1은 거의 안 맞음, 5는 매우 잘 맞음',
    category: 'personality',
    scaleLabels: { low: '잘 안 맞음', high: '잘 맞음' },
    scaleWeights: {
      low: { '丑': 2, '辰': 2, '申': 2, '酉': 1 },
      mid: { '未': 2, '寅': 2, '戌': 2 },
      high: { '子': 3, '巳': 3, '亥': 2, '午': 1 },
    },
  },
]
